### ISSUE TITLE
mkdir LaunchAgents

### ISSUE THREAD

**Issue by ghazel** [DomT4/homebrew-autoupdate#10]
A fresh install of macOS does not have a `~/Library/LaunchAgents` directory. So running autoupdate fails:

```
$ brew autoupdate --start --upgrade --cleanup
Error: No such file or directory @ rb_sysopen - /Users/ghazel/Library/LaunchAgents/com.github.domt4.homebrew-autoupdate.plist
```

Seems like just `mkdir ~/Library/LaunchAgents` fixed it, but it should probably do that automatically.

**Comment by DomT4** [comment]
> A fresh install of macOS does not have a ~/Library/LaunchAgents directory. 

Seriously? 👀. I assumed macOS considered it a kind of "core" directory and ensured it existed, so TIL. I'll push a fix shortly.

**Comment by DomT4** [comment]
Should be fixed via https://github.com/DomT4/homebrew-autoupdate/commit/f066f26ca63fc97e1260acedafa90665c6a699d8. Thanks for the report!
