### ISSUE TITLE
Upgrade brew casks

### ISSUE THREAD

**Issue by ghazel** [DomT4/homebrew-autoupdate#12]
Looks like simply adding:

```ruby
auto_args << " && #{Autoupdate::Core.brew} cask upgrade -v"
```

to the upgrade tasks https://github.com/DomT4/homebrew-autoupdate/blob/e71815f9e0b75a4e639b22d7261c3fdfa6d9eccb/lib/autoupdate/start.rb#L18 would do it.

**Comment by florentroques** [comment]
@DomT4 after merging https://github.com/DomT4/homebrew-autoupdate/pull/13 you can close this issue :)
