### ISSUE TITLE
Warning: Calling `Tap.names` is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by iAGorynT** [DomT4/homebrew-autoupdate#138]
Since updating to MacOS 14.5, I'm receiving the following message when using the `brew autoupdate version` and `brew autoupdate start` commands:

Warning: Calling `Tap.names` is deprecated! There is no replacement.
Please report this issue to the Homebrew/homebrew-autoupdate tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-autoupdate/lib/autoupdate/core.rb:32

Any insights / suggestions would be appreciated.

**Comment by fschlegelone** [comment]
same for me. Are you planning to publish homebrew-autoupdate as official formulae that doesn't require a tap at all?

**Comment by DomT4** [comment]
I'll have a look at Homebrew, see which bit of the API they've changed. Work full time & in the process of moving house so this tap has been a bit neglected recently, apologies.

**Comment by iAGorynT** [comment]
Thanks @DomT4 for the update.  Appreciate your efforts.  As best I can tell, autoupdate continues to run properly with this issue.  At this point, the message seems to be a warning only.  If anyone else has had problems, I'd be interested in hearing what you've experienced.

Thanks to everyone for your insights and comments.

**Comment by DomT4** [comment]
It's a little quick and dirty but this should be resolved now 🤞🏻 . Sorry about that. API change upstream caught me completely unaware.

**Comment by iAGorynT** [comment]
@DomT4 All seems good now.  Autoupdate ran as expected and "Warning: Calling Tap.names is deprecated! " messages aren't appearing. 

Thanks for the fix!

**Comment by allanscullion** [comment]
Nice one mate. Appreciate all the work.
