### ISSUE TITLE
Permission denied when trying to create startup plist file

### ISSUE THREAD

**Issue by mckernanin** [DomT4/homebrew-autoupdate#14]
Just installed on a new machine, and received the following error:

`Error: Permission denied @ rb_sysopen - /Users/kevinmckernan/Library/LaunchAgents/com.github.domt4.homebrew-autoupdate.plist`

Command used:
`brew autoupdate --start --upgrade --cleanup --enable-notification`

I had to create the file with sudo, and then `chown` it to my user.

```
Mac OS 10.13.3
Homebrew 1.5.10
Homebrew/homebrew-core (git revision c7c1; last commit 2018-03-13)
```

**Comment by DomT4** [comment]
This can happen on brand new machines, aye. It's a known thing I haven't yet come to a firm conclusion on how best to handle. I guess I could go down the safest route & try to catch the failure and throw a more helpful message in that situation.

**Comment by DomT4** [comment]
I've gone for a more explicit nudge in https://github.com/DomT4/homebrew-autoupdate/commit/61c26de3456876bf25c7befa977fef5c3d03d9a1, since attempting to create it ourselves seemed to be failing more often than not. Hopefully that at least is a little clearer on how to resolve the issue.
