### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by ishanm0** [DomT4/homebrew-autoupdate#146]
The main README links to [Homebrew Documentation autoupdate subcommand](https://docs.brew.sh/Manpage#autoupdate-subcommand-interval-options) as documentation for using the autoupdate command, however this section of the brew docs has seemingly been removed as of [this PR](https://github.com/Homebrew/brew/pull/16822) in the brew repo.

**Comment by DomT4** [comment]
This has been resolved by https://github.com/DomT4/homebrew-autoupdate/pull/135 being merged 🎉
