### ISSUE TITLE
How do I remove the package?

### ISSUE THREAD

**Issue by nathanael540** [DomT4/homebrew-autoupdate#150]
Excuse me, but how do I remove the package?

**Comment by iAGorynT** [comment]
I believe you should be able to remove the package by removing the Tap. 

Check to see if you have an "autoupdate tap" installed using the following command:
`brew tap`

If you do, check to see if autoupdate is running using the following command:
`brew autoupdate status`

If it is running, stop and delete the autoupdate process using the following commands:
`brew autoupdate stop`
`brew autoupdate delete`

Remove the "autoupdate tap" using the following command:
`brew untap homebrew/autoupdate`

This should remove autoupdate.

If anyone has additional insights, please add your suggestions.

Hope this helps.

**Comment by nathanael540** [comment]
Thank you
