### ISSUE TITLE
Include optional flag for mas

### ISSUE THREAD

**Issue by steakscience** [DomT4/homebrew-autoupdate#16]
Hi there,

First of all, love this repo!

There's a project ([mas-cli](https://github.com/mas-cli/mas)) that allows Mac App Store apps to be installed and updated from the command line. I think homebrew-autoupdate should add an optional flag (say, --mas) that would run 'mas upgrade' as well.

That way, homebrew-autoupdate can be the one place to auto update and upgrade homebrew, casks, and Mac App Store apps.

Thanks!

**Comment by emroch** [comment]
Isn't this handled by the App Store's preference "Automatic Updates"? I don't believe there is a functional difference between an app installed by the App Store GUI and the `mas-cli` tool. I think it is probably better to have the App Store manage its own domain.

**Comment by steakscience** [comment]
True, it'd be nice to have all apps regardless of source updates at once though

Otherwise, it's not a big deal :)
