### ISSUE TITLE
request: cleanup

### ISSUE THREAD

**Issue by plutoniumHead** [DomT4/homebrew-autoupdate#17]
I don't believe the **--cleanup** flag will automatically run the 'cask cleanup' command, so I'm left to do this manually. _OH THE HUMANITY!_ 

Perhaps it can be included with the existing cleanup script– or if that triggers an error for those without any installed casks, perhaps add a separate flag.

**Comment by DomT4** [comment]
Should be fixed via https://github.com/DomT4/homebrew-autoupdate/commit/dda0b33e2fa23530fc82aa469385a87668ff0cd2, Thanks!

**Comment by plutoniumHead** [comment]
Woohoo, thanks!
