### ISSUE TITLE
"brew cask cleanup" is deprecated, breaking notifications if it's last.

### ISSUE THREAD

**Issue by jomymathew** [DomT4/homebrew-autoupdate#19]
`==> No Casks to upgrade`
`Error: Calling "brew cask cleanup" is disabled! Use "brew cleanup" instead.`

/usr/local/bin/brew cask cleanup in the "updater" script errors out and never executes the terminal-notifier command that comes afterwards.

I'm using `brew autoupdate --start 43200 --upgrade --cleanup --enable-notification`

For me, removing the deprecated/disabled (as of 9/30/2018) ` && /usr/local/bin/brew cask cleanup` by (removing line #21 from start.rb) solved the issue.

@DomT4 

more info: https://github.com/Homebrew/brew/issues/4660 & https://github.com/Homebrew/brew/pull/4645

**Comment by DomT4** [comment]
Apologies, GitHub didn't send me a ping on this one for some reason. I'll look into this ASAP.

**Comment by DomT4** [comment]
Fixed via https://github.com/DomT4/homebrew-autoupdate/commit/f54f36c195f2d43fda55acf0e88f4c06e8c3a683. Thanks for the report, and apologies it took a while for me to notice it.
