### ISSUE TITLE
Feature request: Integrate with brew services or provide `status`

### ISSUE THREAD

**Issue by jgogstad** [DomT4/homebrew-autoupdate#22]
Thanks for this, very useful!

Feature request:

Provide users with the ability to see the status of the service (running, stopped, not installed)

Either

1. Integrate with https://github.com/Homebrew/homebrew-services
2. Provide custom command

**Comment by DomT4** [comment]
Implemented a `status` command. Let me know if you hit any issues with it. Thanks for the idea!
