### ISSUE TITLE
Add to Brew/Brew Cask

### ISSUE THREAD

**Issue by FlorianWendelborn** [DomT4/homebrew-autoupdate#23]
Would be great if this would be available in the official brew repository.

**Comment by DomT4** [comment]
For better or worse, I have no desire to work alongside the current Homebrew Project Leader again, which is a feeling that is almost certainly mutual, so this is a request I can't fulfil. Sorry.

**Comment by FlorianWendelborn** [comment]
Fair enough, I know how annoying such a situation can be.

**Comment by DomT4** [comment]
Thanks for understanding, I appreciate that.
