### ISSUE TITLE
Add --greedy --force options for --upgrade

### ISSUE THREAD

**Issue by NathanUrwin** [DomT4/homebrew-autoupdate#30]
Some of my casks require specifying --greedy to upgrade. Please consider adding these options, thanks!

**Comment by Phlogi** [comment]
Could we still have this? I use touch ID for sudo, which solves the blocking #35 . 
https://apple.stackexchange.com/a/306324

**Comment by DomT4** [comment]
Added in https://github.com/DomT4/homebrew-autoupdate/commit/24c4193f89280b3ec38722010623ae2971dc5072.
