### ISSUE TITLE
Calling brew cask upgrade is deprecated! Use brew upgrade --cask instead

### ISSUE THREAD

**Issue by gauthier-roebroeck-mox** [DomT4/homebrew-autoupdate#34]
I get the following in the `.err` log:

```
Updating Homebrew...
Warning: Calling brew cask upgrade is deprecated! Use brew upgrade --cask instead.
```

I'm using the latest Home Brew and just tapped your command today.

**Comment by DomT4** [comment]
Fixed in https://github.com/DomT4/homebrew-autoupdate/commit/f67d8196d713a9c7c478d819f1aea6aad37eee05. Thanks for letting me know @gauthier-roebroeck-mox 🙇‍♂️
