### ISSUE TITLE
Is this persistent on server / computer restarts? 

### ISSUE THREAD

**Issue by D3MZ** [DomT4/homebrew-autoupdate#39]
Thank you for making this! 
Possible to update the readme with this, unsure if I should script this in cron / launchd

**Comment by DomT4** [comment]
Hi @D3MZ. The command itself essentially just creates a `launchd` plist that executes a custom script with whatever commands you've requested this tool to run, with notification support if requested if or running on Big Sur automatically, so the command should run indefinitely until told to stop. I'll amend the README a touch soon to explain better.
